/* DAM OPERATIONS — MOOMA BACKEND MODULE V2 */
const TOKEN_URL="https://oauth2.googleapis.com/token";
const SCOPE="https://www.googleapis.com/auth/spreadsheets";
const DAYS=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
const ROLES=["Team-Member","Acting_Team_Leader","Team_Leader","Acting_Supervisor","Supervisor","Branch_Manager"];
const BAKERY=new Set(["F066","F081","CB054","S019","CB055","CB076","CB056","K154","K256","CB078","CB057","CB072"]);
let cachedToken=null;
const cors=()=>({"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type","Access-Control-Allow-Methods":"GET,POST,DELETE,OPTIONS"});
const json=(x,s=200)=>new Response(JSON.stringify(x,null,2),{status:s,headers:{"Content-Type":"application/json",...cors()}});
const norm=v=>String(v??"").trim().toLowerCase().replace(/\s+|_|-/g,"");
const letters=n=>{let s="";while(n){const r=(n-1)%26;s=String.fromCharCode(65+r)+s;n=Math.floor((n-1)/26)}return s};
const hidx=(h,names)=>{const n=h.map(norm);for(const x of names){const i=n.indexOf(norm(x));if(i>=0)return i}return-1};
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
function parseDate(s){const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(String(s||""));if(!m)throw new Error("Invalid date.");return new Date(+m[1],+m[2]-1,+m[3])}
function week(s){const d=parseDate(s),w=new Date(d);w.setDate(d.getDate()-d.getDay());const dayLabels={};DAYS.forEach((x,i)=>{const z=new Date(w);z.setDate(w.getDate()+i);dayLabels[x]=`${x} (${z.toLocaleDateString("en-GB",{day:"2-digit",month:"short"})})`});const ref=new Date(2026,5,1),diff=Math.floor((w-ref)/(7*86400000));return{weekStartISO:iso(w),weekStartDisplay:w.toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"}),dayLabels,otHeader:diff===0?"Over-Time":`Over-Time ${diff}`}}
function b64(s){return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function buf64(buf){let s="";for(const b of new Uint8Array(buf))s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function pem(p){const c=String(p||"").replace(/\\n/g,"\n").replace(/-----BEGIN PRIVATE KEY-----|-----END PRIVATE KEY-----|\s/g,"");if(!c)throw new Error("MOOMA private key missing.");const b=atob(c),u=new Uint8Array(b.length);for(let i=0;i<b.length;i++)u[i]=b.charCodeAt(i);return u.buffer}
async function token(env){const now=Date.now();if(cachedToken?.expiresAt>now+60000)return cachedToken.token;const email=env.MOOMA_GOOGLE_CLIENT_EMAIL,key=env.MOOMA_GOOGLE_PRIVATE_KEY;if(!email||!key)throw new Error("MOOMA Google credentials missing.");const t=Math.floor(now/1000),a=b64(JSON.stringify({alg:"RS256",typ:"JWT"})),c=b64(JSON.stringify({iss:email,scope:SCOPE,aud:TOKEN_URL,iat:t,exp:t+3600})),unsigned=`${a}.${c}`;const k=await crypto.subtle.importKey("pkcs8",pem(key),{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["sign"]);const sig=await crypto.subtle.sign("RSASSA-PKCS1-v1_5",k,new TextEncoder().encode(unsigned));const r=await fetch(TOKEN_URL,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth:grant-type:jwt-bearer",assertion:`${unsigned}.${buf64(sig)}`})});const x=await r.json();if(!r.ok)throw new Error(x.error_description||x.error||"Google auth failed.");cachedToken={token:x.access_token,expiresAt:now+(x.expires_in||3600)*1000};return x.access_token}
async function read(env,id,range){const r=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}/values/${encodeURIComponent(range)}`,{headers:{Authorization:`Bearer ${await token(env)}`}});const x=await r.json();if(!r.ok)throw new Error(x?.error?.message||"Google read failed.");return x.values||[]}
async function write(env,id,data){const r=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}/values:batchUpdate`,{method:"POST",headers:{Authorization:`Bearer ${await token(env)}`,"Content-Type":"application/json"},body:JSON.stringify({valueInputOption:"USER_ENTERED",data})});const x=await r.json();if(!r.ok)throw new Error(x?.error?.message||"Google write failed.");return x}
async function append(env,id,range,row){const r=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}/values/${encodeURIComponent(range)}:append?valueInputOption=USER_ENTERED&insertDataOption=INSERT_ROWS`,{method:"POST",headers:{Authorization:`Bearer ${await token(env)}`,"Content-Type":"application/json"},body:JSON.stringify({values:[row]})});const x=await r.json();if(!r.ok)throw new Error(x?.error?.message||"Google append failed.");return x}
const master=env=>{if(!env.MOOMA_MASTER_SHEET_ID)throw new Error("MOOMA_MASTER_SHEET_ID missing.");return env.MOOMA_MASTER_SHEET_ID};

async function branchList(env){const rows=await read(env,master(env),"Sheet1!A:Z");if(!rows.length)return[];const h=rows[0],ci=hidx(h,["BranchCode","Branch Code"]),ni=hidx(h,["BranchName","Branch Name"]),si=hidx(h,["SheetID","Sheet ID"]),pi=hidx(h,["Password"]);if(ci<0||ni<0)throw new Error("BranchCode / BranchName missing.");return rows.slice(1).map(r=>({code:String(r[ci]||"").trim().toUpperCase(),name:String(r[ni]||"").trim(),sheetId:si>=0?String(r[si]||"").trim():"",password:pi>=0?String(r[pi]||"").trim():""})).filter(x=>x.code.startsWith("M")&&x.name)}
async function getBranch(env,c){return (await branchList(env)).find(x=>x.code===String(c||"").trim().toUpperCase())||null}
async function login(env,b){const x=await getBranch(env,b.branchCode);if(!x)return{success:false,message:"Branch not found."};if(String(b.password??"")!==x.password)return{success:false,message:"Incorrect password."};return{success:true,branch:{code:x.code,name:x.name}}}

function structure(rows){const a=rows.map(r=>String(r?.[0]||"").trim().toUpperCase()),ds=a.indexOf("DAILY ITEM"),ws=a.indexOf("WEEKLY ITEM");if(ds<0||ws<0)throw new Error("DAILY ITEM or WEEKLY ITEM missing.");const get=(s,e)=>rows.slice(s,e).map((r,i)=>({name:String(r[0]||"").trim(),sku:String(r[1]||"").trim(),uom:String(r[2]||"").trim(),row:s+i+1})).filter(x=>x.name);const bakery=[];rows.forEach((r,i)=>{const sku=String(r?.[1]||"").trim();if(BAKERY.has(sku))bakery.push({name:String(r[0]||"").trim(),sku,uom:String(r[2]||"").trim(),row:i+1})});return{daily:get(ds+1,ws),weekly:get(ws+1,rows.length),bakery,dailyStart:ds,weeklyStart:ws}}
function parseStock(rows){const h=rows[0]||[],cols=h.slice(1),daily=[],weekly=[];let sec=null;for(const r of rows){const t=(r||[]).join(" ").trim().toLowerCase();if(t.includes("daily item")){sec="daily";continue}if(t.includes("weekly item")){sec="weekly";continue}if(!sec||!r?.[0])continue;const o={Item:String(r[0]).trim()};let total=0;cols.forEach((c,i)=>{const v=r[i+1]??"";if(i<2)o[c]=v;else{const n=Number(String(v).replace(/,/g,""))||0;o[c]=n;total+=n}});o.Total=total;(sec==="daily"?daily:weekly).push(o)}return{daily,weekly}}
const drafts=new Map();
async function stockView(env,code){const b=await getBranch(env,code);if(!b?.sheetId)throw new Error("Branch SheetID missing.");return{success:true,source:"MOOMA-GOOGLE",stock:parseStock(await read(env,b.sheetId,"Stocks!A:ZZ"))}}
async function stockInit(env,code,date){const b=await getBranch(env,code);if(!b?.sheetId)throw new Error("Branch SheetID missing.");const rows=await read(env,b.sheetId,"Stocks!A:ZZ"),s=structure(rows),h=rows[0]||[],dc=h.indexOf(date),dup={daily:false,weekly:false,bakery:false};if(dc>=0){for(let i=s.dailyStart+1;i<s.weeklyStart;i++)if(String(rows[i]?.[dc]||"").trim())dup.daily=true;for(let i=s.weeklyStart+1;i<rows.length;i++)if(String(rows[i]?.[dc]||"").trim())dup.weekly=true}const d=m=>drafts.get(`${code}|${date}|${m}`)||null;return{success:true,items:{daily:s.daily,weekly:s.weekly,bakery:s.bakery},duplicate:dup,drafts:{daily:d("daily"),weekly:d("weekly"),bakery:d("bakery")}}}
async function stockSubmit(env,b){const br=await getBranch(env,b.branchCode);if(!br?.sheetId)throw new Error("Branch SheetID missing.");const rows=await read(env,br.sheetId,"Stocks!A:ZZ"),s=structure(rows),h=[...(rows[0]||[])];let ci=h.indexOf(b.date),u=[];if(ci<0){ci=h.length;u.push({range:`Stocks!${letters(ci+1)}1`,values:[[b.date]]})}for(const it of s[b.mode]||[]){if(!(String(it.row) in (b.values||{})))continue;u.push({range:`Stocks!${letters(ci+1)}${it.row}`,values:[[Number(b.values[it.row])||0]]})}if(!u.length)return{success:false,message:"No stock values to submit."};await write(env,br.sheetId,u);drafts.delete(`${b.branchCode}|${b.date}|${b.mode}`);return{success:true,message:`${String(b.mode).toUpperCase()} stock submitted.`}}

async function transferSheet(env){try{return await read(env,master(env),"Transfers!A:Z")}catch{return[]}}
async function transferHeader(env){const r=await transferSheet(env);if(r.length)return r;await write(env,master(env),[{range:"Transfers!A1:H1",values:[["ID","Origin","Destination","Items","Quantities","Reason","Status","Timestamp"]]}]);return [["ID","Origin","Destination","Items","Quantities","Reason","Status","Timestamp"]]}
async function transferInit(env,code){const all=await branchList(env),b=await getBranch(env,code);if(!b?.sheetId)throw new Error("Branch SheetID missing.");const s=structure(await read(env,b.sheetId,"Stocks!A:ZZ"));return{success:true,destinations:all.filter(x=>x.code!==code).map(x=>({code:x.code,name:x.name})),items:[...s.daily,...s.weekly].filter((x,i,a)=>a.findIndex(y=>y.row===x.row)===i)}}
async function transferCreate(env,b){const o=await getBranch(env,b.originBranch),d=await getBranch(env,b.destinationBranch);if(!o||!d)throw new Error("Invalid branch.");const items=(b.items||[]).filter(x=>Number(x.qty)>0);if(!items.length)return{success:false,message:"Enter transfer quantity."};const rows=await read(env,o.sheetId,"Stocks!A:ZZ"),h=rows[0]||[],date=iso(new Date(Date.now()-86400000)),ci=h.indexOf(date);if(ci<0)throw new Error(`Stock date ${date} not found.`);const s=structure(rows),map=new Map([...s.daily,...s.weekly].map(x=>[`${x.name}|${x.sku}`,x])),u=[];for(const x of items){const it=map.get(`${x.name}|${x.sku}`);if(!it)continue;const cur=Number(rows[it.row-1]?.[ci]||0)||0;u.push({range:`Stocks!${letters(ci+1)}${it.row}`,values:[[cur-Number(x.qty)]]})}if(u.length)await write(env,o.sheetId,u);await transferHeader(env);const id=`MTR-${Date.now()}`;await append(env,master(env),"Transfers!A:H",[id,`${o.code} - ${o.name}`,`${d.code} - ${d.name}`,items.map(x=>`• ${x.name} [${x.sku}]`).join("\n"),items.map(x=>x.qty).join("\n"),b.reason||"","Pending",new Date().toISOString()]);return{success:true,id,message:"MOOMA transfer created."}}
async function transferHistory(env,code,limit=10,pendingOnly=false){const rows=await transferSheet(env);if(rows.length<2)return{success:true,total:0,transfers:[]};const h=rows[0].map(norm),i=n=>h.indexOf(norm(n)),ii=i("ID"),oi=i("Origin"),di=i("Destination"),iti=i("Items"),qi=i("Quantities"),si=i("Status"),ti=i("Timestamp");let a=rows.slice(1).map(r=>({id:r[ii],origin:r[oi],destination:r[di],items:r[iti],quantities:r[qi],status:r[si],updated_at:r[ti]})).filter(x=>pendingOnly?(String(x.destination).startsWith(code)&&x.status==="Pending"):(String(x.origin).startsWith(code)||String(x.destination).startsWith(code))).reverse();return{success:true,total:a.length,transfers:a.slice(0,limit)}}
async function transferRespond(env,b){const rows=await transferSheet(env),h=rows[0]?.map(norm)||[],ii=h.indexOf("id"),si=h.indexOf("status");let ri=-1;for(let i=1;i<rows.length;i++)if(String(rows[i]?.[ii]||"")===b.transferId){ri=i;break}if(ri<0)throw new Error("Transfer not found.");const status=b.action==="accept"?"Accepted":"Rejected";await write(env,master(env),[{range:`Transfers!${letters(si+1)}${ri+1}`,values:[[status]]}]);return{success:true,status,message:`Transfer ${status.toLowerCase()}.`}}

const empId=h=>hidx(h,["Employee ID","EmployeeID","Staff ID","Emp ID","ID"]);
async function scheduleRows(env){return read(env,master(env),"StaffSchedule!A:ZZ")}
function scheduleParse(rows,code,date){if(!rows.length)throw new Error("StaffSchedule is empty.");const h=rows[0],n=h.map(norm),bi=n.indexOf("branch"),ni=n.indexOf("name"),ri=n.indexOf("role"),ei=empId(h);if(bi<0||ni<0||ri<0)throw new Error("StaffSchedule requires Branch, Name and Role.");const w=week(date),di=Object.fromEntries(DAYS.map(d=>[d,h.indexOf(w.dayLabels[d])])),oi=h.indexOf(w.otHeader);let submitted=false;const employees=[];for(let i=1;i<rows.length;i++){const r=rows[i]||[],rb=String(r[bi]||"").trim().toUpperCase();if(!(rb===code||rb.startsWith(`${code} `)||rb.startsWith(`${code}-`)))continue;const name=String(r[ni]||"").trim();if(!name)continue;const shifts={};DAYS.forEach(d=>{shifts[d]=di[d]>=0?String(r[di[d]]||""):"";if(shifts[d].trim())submitted=true});employees.push({rowNumber:i+1,employeeId:ei>=0?String(r[ei]||"").trim():"",name,role:String(r[ri]||"").trim(),shifts,overtime:oi>=0?String(r[oi]||"").trim():"0 hrs"})}return{week:w,headers:h,employees,submitted}}
async function scheduleHeaders(env,rows,w){const h=[...(rows[0]||[])],u=[];for(const d of DAYS){const x=w.dayLabels[d];if(!h.includes(x)){u.push({range:`StaffSchedule!${letters(h.length+1)}1`,values:[[x]]});h.push(x)}}if(!h.includes(w.otHeader)){u.push({range:`StaffSchedule!${letters(h.length+1)}1`,values:[[w.otHeader]]});h.push(w.otHeader)}if(u.length)await write(env,master(env),u);return h}
function calcOT(shifts){let t=0;DAYS.forEach(d=>{const m=/\(OT\s+(\d+(?:\.\d+)?)\s*h\)/i.exec(String(shifts?.[d]||""));if(m)t+=Number(m[1])||0});return t}
async function scheduleInit(env,code,date){const b=await getBranch(env,code);if(!b)throw new Error("Branch not found.");return{success:true,source:"MOOMA-GOOGLE",branch:{code:b.code,name:b.name},...scheduleParse(await scheduleRows(env),code,date),roles:ROLES,destinations:(await branchList(env)).filter(x=>x.code!==code).map(x=>({code:x.code,name:x.name,label:`${x.code} - ${x.name}`}))}}
async function scheduleSubmit(env,b){const rows=await scheduleRows(env),cur=scheduleParse(rows,b.branchCode,b.selectedDate);if(cur.submitted)return{success:false,message:"This week's schedule has already been submitted for this branch."};const w=week(b.selectedDate),h=await scheduleHeaders(env,rows,w),n=h.map(norm),bi=n.indexOf("branch"),ni=n.indexOf("name"),ri=n.indexOf("role"),ei=empId(h),sheet=rows.slice(1),u=[];for(const e of b.employees||[]){let rn=null;for(let i=0;i<sheet.length;i++){const r=sheet[i]||[],bm=String(r[bi]||"").trim().toUpperCase()===b.branchCode,im=ei>=0&&e.employeeId&&String(r[ei]||"").trim()===String(e.employeeId),nm=String(r[ni]||"").trim()===String(e.name||"").trim();if(bm&&(im||nm)){rn=i+2;break}}if(!rn){rn=sheet.length+2;sheet.push([]);u.push({range:`StaffSchedule!${letters(bi+1)}${rn}`,values:[[b.branchCode]]},{range:`StaffSchedule!${letters(ni+1)}${rn}`,values:[[e.name]]})}u.push({range:`StaffSchedule!${letters(ri+1)}${rn}`,values:[[e.role||"Team-Member"]]});if(ei>=0&&e.employeeId)u.push({range:`StaffSchedule!${letters(ei+1)}${rn}`,values:[[e.employeeId]]});for(const d of DAYS){const ci=h.indexOf(w.dayLabels[d]);u.push({range:`StaffSchedule!${letters(ci+1)}${rn}`,values:[[e.shifts?.[d]||""]]})}const oi=h.indexOf(w.otHeader);u.push({range:`StaffSchedule!${letters(oi+1)}${rn}`,values:[[`${calcOT(e.shifts)} hrs`]]})}if(u.length)await write(env,master(env),u);return{success:true,weekStartDisplay:w.weekStartDisplay,message:"Schedule submitted successfully."}}
async function addEmployee(env,b){const rows=await scheduleRows(env),h=[...(rows[0]||[])];let ei=empId(h);if(ei<0){ei=h.length;await write(env,master(env),[{range:`StaffSchedule!${letters(ei+1)}1`,values:[["Employee ID"]]}]);h.push("Employee ID")}const n=h.map(norm),bi=n.indexOf("branch"),ni=n.indexOf("name"),ri=n.indexOf("role");const row=Array(h.length).fill("");row[bi]=b.branchCode;row[ni]=b.name;row[ri]=b.role;row[ei]=b.employeeId||"";await append(env,master(env),"StaffSchedule!A:ZZ",row);return{success:true,message:`${b.name} added.`}}
async function removeEmployee(env,b){const rows=await scheduleRows(env),h=rows[0]||[],n=h.map(norm),bi=n.indexOf("branch"),ni=n.indexOf("name"),ei=empId(h);let rn=-1;for(let i=1;i<rows.length;i++){const r=rows[i]||[];if(String(r[bi]||"").trim().toUpperCase()!==b.branchCode)continue;const idok=ei>=0&&b.employeeId&&String(r[ei]||"").trim()===String(b.employeeId),nameok=String(r[ni]||"").trim()===String(b.name||"").trim();if(idok||nameok){rn=i+1;break}}if(rn<0)throw new Error("Employee not found.");if(b.reason==="transfer"){await write(env,master(env),[{range:`StaffSchedule!${letters(bi+1)}${rn}`,values:[[b.destinationBranch]]}]);return{success:true,message:`${b.name} transferred to ${b.destinationBranch}.`}}const u=[{range:`StaffSchedule!${letters(bi+1)}${rn}`,values:[[""]]}];if(b.reason==="contract_finished"&&ei>=0)u.push({range:`StaffSchedule!${letters(ei+1)}${rn}`,values:[[""]]});await write(env,master(env),u);return{success:true,message:`${b.name} removed from active branch.`}}

export async function handleMoomaRequest(request,env){const url=new URL(request.url);if(request.method==="OPTIONS")return new Response(null,{status:204,headers:cors()});try{
 if(url.pathname==="/api/mooma/test")return json({success:true,version:"MOOMA-BACKEND-V2",message:"MOOMA backend connected",envCheck:{MOOMA_GOOGLE_CLIENT_EMAIL:Boolean(env.MOOMA_GOOGLE_CLIENT_EMAIL),MOOMA_GOOGLE_PRIVATE_KEY:Boolean(env.MOOMA_GOOGLE_PRIVATE_KEY),MOOMA_MASTER_SHEET_ID:Boolean(env.MOOMA_MASTER_SHEET_ID)}});
 if(url.pathname==="/api/mooma/branches"&&request.method==="GET"){const a=await branchList(env);return json({success:true,source:"MOOMA-GOOGLE",count:a.length,branches:a.map(({password,...x})=>x)})}
 if(url.pathname==="/api/mooma/login"&&request.method==="POST"){const r=await login(env,await request.json());return json(r,r.success?200:401)}
 if(url.pathname==="/api/mooma/stock-view"&&request.method==="GET")return json(await stockView(env,url.searchParams.get("branch")));
 if(url.pathname==="/api/mooma/stock-record/init"&&request.method==="GET")return json(await stockInit(env,String(url.searchParams.get("branch")||"").toUpperCase(),url.searchParams.get("date")));
 if(url.pathname==="/api/mooma/stock-record/draft"&&request.method==="POST"){const b=await request.json();drafts.set(`${b.branchCode}|${b.date}|${b.mode}`,{values:b.values||{},updatedAt:Date.now()});return json({success:true,message:"Draft saved."})}
 if(url.pathname==="/api/mooma/stock-record/draft"&&request.method==="DELETE"){const b=await request.json();drafts.delete(`${b.branchCode}|${b.date}|${b.mode}`);return json({success:true,message:"Draft deleted."})}
 if(url.pathname==="/api/mooma/stock-record/submit"&&request.method==="POST"){const r=await stockSubmit(env,await request.json());return json(r,r.success?200:409)}
 if(url.pathname==="/api/mooma/stock-transfer/init"&&request.method==="GET")return json(await transferInit(env,String(url.searchParams.get("branch")||"").toUpperCase()));
 if(url.pathname==="/api/mooma/stock-transfer/create"&&request.method==="POST"){const r=await transferCreate(env,await request.json());return json(r,r.success?200:409)}
 if(url.pathname==="/api/mooma/stock-transfer/history"&&request.method==="GET")return json(await transferHistory(env,String(url.searchParams.get("branch")||"").toUpperCase(),Math.min(50,Number(url.searchParams.get("limit")||10)),false));
 if(url.pathname==="/api/mooma/pending-transfers"&&request.method==="GET")return json(await transferHistory(env,String(url.searchParams.get("branch")||"").toUpperCase(),50,true));
 if(url.pathname==="/api/mooma/transfer/respond"&&request.method==="POST")return json(await transferRespond(env,await request.json()));
 if(url.pathname==="/api/mooma/schedule/init"&&request.method==="GET")return json(await scheduleInit(env,String(url.searchParams.get("branch")||"").toUpperCase(),String(url.searchParams.get("date")||"")));
 if(url.pathname==="/api/mooma/schedule/submit"&&request.method==="POST"){const r=await scheduleSubmit(env,await request.json());return json(r,r.success?200:409)}
 if(url.pathname==="/api/mooma/schedule/employee/add"&&request.method==="POST")return json(await addEmployee(env,await request.json()));
 if(url.pathname==="/api/mooma/schedule/employee/remove"&&request.method==="POST")return json(await removeEmployee(env,await request.json()));
 return json({success:false,message:"MOOMA route not found."},404);
}catch(e){console.error("MOOMA BACKEND ERROR",e);return json({success:false,message:e?.message||"MOOMA backend error."},500)}}
