import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, RefreshCcw, Save, Trash2 } from "lucide-react";
import { moomaFetch } from "./moomaApi.js";
import "./MoomaStockRecord.css";
const MODES=["daily","weekly","bakery"];
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
export default function MoomaStockRecord({branch,onBack}){
 const [date,setDate]=useState(today()),[mode,setMode]=useState("daily"),[data,setData]=useState(null),[values,setValues]=useState({}),[busy,setBusy]=useState(false),[message,setMessage]=useState(null);
 async function load(force=false){try{setBusy(true);setMessage(null);const r=await moomaFetch(`/api/mooma/stock-record/init?branch=${encodeURIComponent(branch.code)}&date=${date}${force?"&refresh=1":""}`);setData(r);setValues(r.drafts?.[mode]?.values||{})}catch(e){setMessage({type:"error",text:e.message})}finally{setBusy(false)}}
 useEffect(()=>{load(false)},[branch?.code,date]);useEffect(()=>{if(data)setValues(data.drafts?.[mode]?.values||{})},[mode]);
 const items=useMemo(()=>data?.items?.[mode]||[],[data,mode]);
 async function save(){try{setBusy(true);await moomaFetch("/api/mooma/stock-record/draft",{method:"POST",body:JSON.stringify({branchCode:branch.code,date,mode,values})});setMessage({type:"success",text:"Draft saved."})}catch(e){setMessage({type:"error",text:e.message})}finally{setBusy(false)}}
 async function clear(){if(!confirm("Delete this draft?"))return;try{setBusy(true);await moomaFetch("/api/mooma/stock-record/draft",{method:"DELETE",body:JSON.stringify({branchCode:branch.code,date,mode})});setValues({});setMessage({type:"success",text:"Draft cleared."})}catch(e){setMessage({type:"error",text:e.message})}finally{setBusy(false)}}
 async function submit(){if(!confirm(`Submit ${mode.toUpperCase()} stock for ${date}?`))return;try{setBusy(true);const r=await moomaFetch("/api/mooma/stock-record/submit",{method:"POST",body:JSON.stringify({branchCode:branch.code,date,mode,values})});setMessage({type:"success",text:r.message});await load(true)}catch(e){setMessage({type:"error",text:e.message})}finally{setBusy(false)}}
 return <div className="mm-page"><header className="mm-head"><button onClick={onBack}><ArrowLeft size={15}/> DASHBOARD</button><strong>MOOMA · STOCK RECORD</strong><button onClick={()=>load(true)}><RefreshCcw size={15}/> REFRESH</button></header><main className="mm-main"><div className="mm-title"><small>{branch.code} / {branch.name}</small><h1>Record stock.</h1><p>Daily, weekly and bakery entries.</p></div>{message&&<div className={`mm-msg ${message.type}`}>{message.text}</div>}<section className="mm-panel"><div className="mm-toolbar"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><div className="mm-tabs">{MODES.map(m=><button className={m===mode?"active":""} key={m} onClick={()=>setMode(m)}>{m.toUpperCase()}</button>)}</div><button className="mm-btn" onClick={save} disabled={busy}><Save size={14}/> SAVE DRAFT</button><button className="mm-btn danger" onClick={clear} disabled={busy}><Trash2 size={14}/> CLEAR</button><button className="mm-btn primary" onClick={submit} disabled={busy||data?.duplicate?.[mode]}>{data?.duplicate?.[mode]?"ALREADY SUBMITTED":"SUBMIT"}</button></div><div className="mm-table-wrap"><table className="mm-table"><thead><tr><th>ITEM</th><th>SKU</th><th>UOM</th><th>QTY</th></tr></thead><tbody>{items.map(it=><tr key={`${it.row}-${it.sku}`}><td>{it.name}</td><td>{it.sku}</td><td>{it.uom}</td><td><input className="mm-qty" type="number" step="any" value={values[it.row]??""} onChange={e=>setValues(v=>({...v,[it.row]:e.target.value}))}/></td></tr>)}</tbody></table></div>{!busy&&!items.length&&<div className="mm-empty">No items found.</div>}</section></main></div>
}
