import { useEffect, useMemo, useRef, useState } from "react";
import { motion } from "framer-motion";
import { AlertCircle, ArrowLeft, ArrowRight, Eye, EyeOff, LoaderCircle, MapPin, RefreshCcw, Search } from "lucide-react";
import { moomaFetch } from "./moomaApi.js";
import MoomaDashboard from "./MoomaDashboard.jsx";
import "./MoomaPortal.css";
export default function MoomaPortal({onBack}){
 const [branches,setBranches]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[search,setSearch]=useState(""),[selected,setSelected]=useState(null),[auth,setAuth]=useState(null),[password,setPassword]=useState(""),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[loginError,setLoginError]=useState("");const ready=useRef(null);
 async function load(){try{setLoading(true);setError("");const r=await moomaFetch("/api/mooma/branches");setBranches(r.branches||[])}catch(e){setError(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[]);
 const visible=useMemo(()=>{const q=search.trim().toLowerCase();return q?branches.filter(b=>`${b.code} ${b.name}`.toLowerCase().includes(q)):branches},[branches,search]);
 function select(b){setSelected(b);setTimeout(()=>ready.current?.scrollIntoView({behavior:"smooth",block:"center"}),150)}
 async function login(){try{setBusy(true);setLoginError("");const r=await moomaFetch("/api/mooma/login",{method:"POST",body:JSON.stringify({branchCode:selected.code,password})});setAuth(r.branch)}catch(e){setLoginError(e.message)}finally{setBusy(false)}}
 if(auth)return <MoomaDashboard branch={auth} onBack={()=>setAuth(null)} onLogout={()=>{setAuth(null);setSelected(null);setPassword("")}}/>;
 return <div className="mooma-page"><header className="mooma-top"><button onClick={onBack}><ArrowLeft size={15}/> ALL BRANDS</button><strong>MOOMA · BRANCH ACCESS</strong><span>● LIVE</span></header><main className="mooma-main"><section className="mooma-hero"><div><small>MOOMA / STAFF NETWORK</small><h1>Choose your <em>branch.</em></h1><p>Select a branch and authenticate.</p></div><div className="mooma-count"><small>LIVE DIRECTORY</small><b>{loading?"…":branches.length}</b><span>MOOMA LOCATIONS</span></div></section><section className="mooma-box"><div className="mooma-search"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search MOOMA branches"/><span>{visible.length} LOCATIONS</span></div>{loading?<div className="mooma-state"><LoaderCircle className="spin"/><b>CONNECTING MOOMA NETWORK</b></div>:error?<div className="mooma-state"><AlertCircle/><b>CONNECTION FAILED</b><small>{error}</small><button onClick={load}><RefreshCcw size={14}/> RETRY</button></div>:<><div className="mooma-list">{visible.map((b,i)=><motion.button key={b.code} className={selected?.code===b.code?"active":""} onClick={()=>select(b)} initial={{opacity:0,x:-12}} animate={{opacity:1,x:0}} transition={{delay:i*.04}}><span>{String(i+1).padStart(2,"0")}</span><MapPin size={16}/><div><b>{b.name}</b><small>{b.code}</small></div><ArrowRight size={15}/></motion.button>)}</div>{selected&&<motion.div ref={ready} className="mooma-ready" initial={{opacity:0,y:14}} animate={{opacity:1,y:0}}><div><small>READY TO ENTER</small><b>{selected.code} • {selected.name}</b>{loginError&&<i>{loginError}</i>}</div><div className="mooma-login"><label><input type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Branch password"/><button onClick={()=>setShow(v=>!v)}>{show?<EyeOff size={14}/>:<Eye size={14}/>}</button></label><button className="continue" disabled={!password||busy} onClick={login}>{busy?<LoaderCircle size={15}/>:<>CONTINUE <ArrowRight size={15}/></>}</button></div></motion.div>}</>}</section></main></div>
}
