import { useEffect, useMemo, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowLeft, ArrowRight, CheckCircle2, History, LoaderCircle, MapPin, PackagePlus, RefreshCcw, Search, Send, Sparkles, Trash2, Truck, X } from "lucide-react";
import { activeScroll, moomaFetch } from "./moomaApi.js";
import MoomaLoading from "./MoomaLoading.jsx";
export default function MoomaStockTransfer({branch,onBack}){
 const [data,setData]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[destination,setDestination]=useState(""),[search,setSearch]=useState(""),[cart,setCart]=useState([]),[reason,setReason]=useState(""),[history,setHistory]=useState([]),[message,setMessage]=useState(null),[showHistory,setShowHistory]=useState(false);
 const cartRef=useRef(null),historyRef=useRef(null),messageRef=useRef(null);
 async function load(){try{setLoading(true);setMessage(null);const [r,h]=await Promise.all([moomaFetch(`/api/mooma/stock-transfer/init?branch=${encodeURIComponent(branch.code)}`),moomaFetch(`/api/mooma/stock-transfer/history?branch=${encodeURIComponent(branch.code)}&limit=20`)]);setData(r);setHistory(h.transfers||[])}catch(e){setMessage({type:"error",text:e.message});activeScroll(messageRef)}finally{setLoading(false)}}
 useEffect(()=>{load()},[branch?.code]);const items=useMemo(()=>{const a=data?.items||[],q=search.trim().toLowerCase();return q?a.filter(x=>`${x.name} ${x.sku} ${x.uom}`.toLowerCase().includes(q)):a},[data,search]);
 function add(item){setCart(c=>c.some(x=>x.row===item.row)?c:[...c,{...item,qty:""}]);setTimeout(()=>activeScroll(cartRef,"center"),50)}
 function remove(row){setCart(c=>c.filter(x=>x.row!==row));activeScroll(cartRef,"center")}
 async function create(){if(!destination||!cart.some(x=>Number(x.qty)>0)||busy)return;try{setBusy(true);const r=await moomaFetch("/api/mooma/stock-transfer/create",{method:"POST",body:JSON.stringify({originBranch:branch.code,destinationBranch:destination,reason,items:cart.filter(x=>Number(x.qty)>0).map(x=>({name:x.name,sku:x.sku,uom:x.uom,qty:Number(x.qty)}))})});setMessage({type:"success",text:r.message||"Transfer created successfully."});setCart([]);setDestination("");setReason("");activeScroll(messageRef);await load()}catch(e){setMessage({type:"error",text:e.message});activeScroll(messageRef)}finally{setBusy(false)}}
 if(loading&&!data)return <div className="bst-page"><MoomaLoading label="LOADING STOCK TRANSFER"/></div>;
 return <motion.div className="bst-page" initial={{opacity:0,scale:1.008,filter:"blur(8px)"}} animate={{opacity:1,scale:1,filter:"blur(0px)"}}><div className="bst-grid-bg"/><div className="bst-orb bst-orb-one"/><div className="bst-orb bst-orb-two"/><header className="bst-header"><button className="bst-back" onClick={onBack}><ArrowLeft size={15}/> DASHBOARD</button><div className="bst-brand"><div>M</div><span><strong>MOOMA</strong><small>STOCK TRANSFER</small></span></div><button className="bst-history-button" onClick={()=>{setShowHistory(v=>!v);setTimeout(()=>activeScroll(historyRef,"start"),60)}}><History size={14}/> HISTORY</button></header>
 <main className="bst-main"><div ref={messageRef}>{message&&<div className={`bst-message ${message.type}`}>{message.type==="success"?<CheckCircle2 size={14}/>:<X size={14}/>} {message.text}</div>}</div><section className="bst-hero"><div><span className="bst-eyebrow"><Sparkles size={13}/> INTERNAL STOCK MOVEMENT</span><h1>Move stock <span>cleanly.</span></h1><p>Same BART transfer flow: select destination, add items, review cart and submit.</p></div><div className="bst-route-card"><small>ORIGIN BRANCH</small><strong>{branch.code}</strong><span>{branch.name}</span></div></section>
 <section className="bst-transfer-layout"><div className="bst-catalog"><div className="bst-section-head"><div><small>01 / ITEMS</small><h2>Select stock.</h2></div><strong>{items.length} ITEMS</strong></div><div className="bst-controls"><div className="bst-search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search item / SKU"/></div><select value={destination} onChange={e=>{setDestination(e.target.value);setTimeout(()=>activeScroll(cartRef,"center"),50)}}><option value="">SELECT DESTINATION</option>{(data?.destinations||[]).map(d=><option key={d.code} value={d.code}>{d.code} - {d.name}</option>)}</select></div><div className="bst-items-grid">{items.map((item,i)=><motion.button key={`${item.row}-${item.sku}`} className={cart.some(x=>x.row===item.row)?"selected":""} onClick={()=>add(item)} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:Math.min(i*.012,.22)}}><small>{item.sku}</small><strong>{item.name}</strong><span>{item.uom}</span><div><PackagePlus size={14}/> ADD</div></motion.button>)}</div></div>
 <aside ref={cartRef} className="bst-cart"><div className="bst-cart-head"><div><small>02 / CART</small><h2>Transfer cart.</h2></div><strong>{cart.length}</strong></div>{!cart.length?<div className="bst-empty-cart"><Truck size={27}/><strong>NO ITEMS YET</strong><span>Tap ADD and the screen will bring you here automatically.</span></div>:<div className="bst-cart-list">{cart.map(x=><motion.div key={x.row} className="bst-cart-item" initial={{opacity:0,x:15}} animate={{opacity:1,x:0}}><div><strong>{x.name}</strong><small>{x.sku} · {x.uom}</small></div><input inputMode="decimal" type="number" step="any" value={x.qty} onChange={e=>setCart(c=>c.map(y=>y.row===x.row?{...y,qty:e.target.value}:y))} placeholder="QTY"/><button onClick={()=>remove(x.row)}><Trash2 size={13}/></button></motion.div>)}</div>}<label className="bst-reason"><span>REASON / REFERENCE</span><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Optional transfer note"/></label><button className="bst-send" disabled={!destination||!cart.some(x=>Number(x.qty)>0)||busy} onClick={create}>{busy?<LoaderCircle className="dam-spin" size={16}/>:<Send size={16}/>} SEND TRANSFER <ArrowRight size={15}/></button></aside></section>
 <AnimatePresence>{showHistory&&<motion.section ref={historyRef} className="bst-history" initial={{opacity:0,y:18}} animate={{opacity:1,y:0}}><div className="bst-section-head"><div><small>TRANSFER ARCHIVE</small><h2>Recent history.</h2></div><button onClick={load}><RefreshCcw size={14}/> REFRESH</button></div><div className="bst-history-table"><table><thead><tr><th>ID</th><th>ORIGIN</th><th>DESTINATION</th><th>STATUS</th><th>TIME</th></tr></thead><tbody>{history.map(x=><tr key={x.id}><td>{x.id}</td><td>{x.origin}</td><td>{x.destination}</td><td>{x.status}</td><td>{x.updated_at||x.timestamp||"-"}</td></tr>)}</tbody></table></div></motion.section>}</AnimatePresence>
 </main></motion.div>
}
