import { useEffect, useMemo, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowLeft, ArrowRight, CheckCircle2, ClipboardList, LoaderCircle, RefreshCcw, RotateCcw, Search, Sparkles, XCircle } from "lucide-react";
import { activeScroll, moomaFetch } from "./moomaApi.js";
import MoomaLoading from "./MoomaLoading.jsx";

const MODES=[{id:"daily",number:"01",title:"Daily Stock",sub:"DAILY ITEM",copy:"Record today's daily operational stock."},{id:"weekly",number:"02",title:"Weekly Stock",sub:"WEEKLY ITEM",copy:"Record weekly inventory items."},{id:"bakery",number:"03",title:"Bakery",sub:"BAKERY ITEMS",copy:"Record the bakery SKU set."}];
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
export default function MoomaStockRecord({branch,onBack}){
 const [date,setDate]=useState(today()),[mode,setMode]=useState(null),[data,setData]=useState(null),[values,setValues]=useState({}),[search,setSearch]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[review,setReview]=useState(false),[message,setMessage]=useState(null);
 const entryRef=useRef(null),reviewRef=useRef(null),messageRef=useRef(null);
 async function load(force=false){try{setLoading(true);setMessage(null);const r=await moomaFetch(`/api/mooma/stock-record/init?branch=${encodeURIComponent(branch.code)}&date=${encodeURIComponent(date)}${force?"&refresh=1":""}`);setData(r);if(mode)setValues(r.drafts?.[mode]?.values||{})}catch(e){setMessage({type:"error",text:e.message});activeScroll(messageRef)}finally{setLoading(false)}}
 useEffect(()=>{load(false)},[branch?.code,date]);
 function chooseMode(id){setMode(id);setReview(false);setValues(data?.drafts?.[id]?.values||{});setTimeout(()=>activeScroll(entryRef,"start"),60)}
 const items=useMemo(()=>{const a=data?.items?.[mode]||[],q=search.trim().toLowerCase();return q?a.filter(x=>`${x.name} ${x.sku} ${x.uom}`.toLowerCase().includes(q)):a},[data,mode,search]);
 const entered=useMemo(()=>Object.entries(values).filter(([,v])=>String(v).trim()!=="").length,[values]);
 async function saveDraft(){if(!mode)return;try{setBusy(true);const r=await moomaFetch("/api/mooma/stock-record/draft",{method:"POST",body:JSON.stringify({branchCode:branch.code,date,mode,values})});setMessage({type:"success",text:r.message||"Draft saved."});activeScroll(messageRef)}catch(e){setMessage({type:"error",text:e.message});activeScroll(messageRef)}finally{setBusy(false)}}
 function showReview(){setReview(true);setTimeout(()=>activeScroll(reviewRef,"start"),50)}
 async function clearAll(){if(!confirm("Clear all entered values for this mode?"))return;setValues({});setReview(false);try{await moomaFetch("/api/mooma/stock-record/draft",{method:"DELETE",body:JSON.stringify({branchCode:branch.code,date,mode})})}catch{}}
 async function submit(){if(busy)return;if(!confirm(`Submit ${mode?.toUpperCase()} stock for ${date}?`))return;try{setBusy(true);const r=await moomaFetch("/api/mooma/stock-record/submit",{method:"POST",body:JSON.stringify({branchCode:branch.code,date,mode,values})});setMessage({type:"success",text:r.message||"Stock submitted successfully."});setReview(false);activeScroll(messageRef);await load(true)}catch(e){setMessage({type:"error",text:e.message});activeScroll(messageRef)}finally{setBusy(false)}}
 if(loading&&!data)return <div className="bart-stock-record"><MoomaLoading label="LOADING STOCK RECORD"/></div>;
 return <motion.div className="bart-stock-record" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}}><div className="bsr-grid-bg"/><div className="bsr-orb bsr-orb-one"/><div className="bsr-orb bsr-orb-two"/>
  <header className="bsr-header"><button className="bsr-back" onClick={onBack}><ArrowLeft size={15}/> DASHBOARD</button><div className="bsr-brand"><ClipboardList size={17}/><span><strong>MOOMA</strong><small>STOCK RECORD</small></span></div><div className="bsr-branch-chip"><span/>{branch.code} · {branch.name}</div></header>
  <main className="bsr-main"><div ref={messageRef}>{message&&<div className={`bsr-message ${message.type}`}>{message.type==="success"?<CheckCircle2 size={15}/>:<XCircle size={15}/>} {message.text}</div>}</div>
   {!mode?<section className="bsr-mode-page"><span className="bsr-eyebrow"><Sparkles size={13}/> STOCK OPERATIONS</span><h1>What are you <span>recording?</span></h1><p className="bsr-lead">Choose the same stock workflow used in BART.</p><div className="bsr-date-panel"><div><small>STOCK DATE</small><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><button onClick={()=>load(true)}><RefreshCcw size={15}/> REFRESH</button></div><div className="bsr-mode-grid">{MODES.map((m,i)=><motion.button key={m.id} className="bsr-mode-card" onClick={()=>chooseMode(m.id)} initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{delay:.08*i}} whileHover={{y:-6}}><span className="bsr-mode-number">{m.number}</span><span className="bsr-mode-subtitle">{m.sub}</span><h2>{m.title}</h2><p>{m.copy}</p><div className="bsr-mode-open">OPEN MODULE <ArrowRight size={16}/></div></motion.button>)}</div></section>:
   <section ref={entryRef} className="bsr-entry-page"><div className="bsr-entry-top"><div><span className="bsr-eyebrow">{mode.toUpperCase()} / {date}</span><h1>{MODES.find(x=>x.id===mode)?.title}</h1><p>{entered} of {(data?.items?.[mode]||[]).length} items entered</p></div><button className="bsr-change-mode" onClick={()=>{setMode(null);setReview(false);window.scrollTo({top:0,behavior:"smooth"})}}><RotateCcw size={14}/> CHANGE MODE</button></div>
    <div className="bsr-toolbar"><div className="bsr-search"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search item or SKU"/></div><button className="bsr-clear" onClick={clearAll}>CLEAR ALL</button><button className="bsr-save-draft" onClick={saveDraft} disabled={busy}>SAVE DRAFT</button></div>
    <div className="bsr-item-grid">{items.map((item,i)=><motion.div className="bsr-item-card" key={`${item.row}-${item.sku}`} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:Math.min(i*.015,.25)}}><small>{item.sku||"NO SKU"}</small><strong>{item.name}</strong><span>{item.uom||"UOM"}</span><input type="number" step="any" inputMode="decimal" value={values[item.row]??""} onChange={e=>setValues(v=>({...v,[item.row]:e.target.value}))} placeholder="0"/></motion.div>)}</div>
    <div className="bsr-action-bar"><button onClick={saveDraft} disabled={busy}>SAVE DRAFT</button><button className="primary" onClick={showReview} disabled={!entered}>REVIEW {entered} ITEMS <ArrowRight size={15}/></button></div>
    <AnimatePresence>{review&&<motion.section ref={reviewRef} className="bsr-review" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}><div className="bsr-review-head"><div><span>FINAL REVIEW</span><h2>Confirm stock entry.</h2></div><strong>{entered} ITEMS</strong></div><div className="bsr-review-grid">{(data?.items?.[mode]||[]).filter(it=>String(values[it.row]??"").trim()!=="").map(it=><div className="bsr-review-card" key={it.row}><small>{it.sku}</small><strong>{it.name}</strong><span>{values[it.row]} {it.uom}</span></div>)}</div><div className="bsr-submit-row"><button onClick={()=>{setReview(false);activeScroll(entryRef,"start")}}>BACK TO EDIT</button><button className="primary" onClick={submit} disabled={busy||data?.duplicate?.[mode]}>{busy?<LoaderCircle className="dam-spin" size={15}/>:<CheckCircle2 size={15}/>} {data?.duplicate?.[mode]?"ALREADY SUBMITTED":"SUBMIT TO GOOGLE SHEET"}</button></div></motion.section>}</AnimatePresence>
   </section>}
  </main></motion.div>
}
