import { useEffect, useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import {
  Activity, AlertTriangle, ArrowLeft, ArrowRight, BarChart3, Boxes, Building2, CalendarDays,
  ChartNoAxesCombined, ChevronDown, ChevronRight, CircleGauge, ClipboardCheck, Command, Database,
  Download, Eye, EyeOff, FileChartColumn, FileSpreadsheet, Filter, Gauge, GitCompareArrows, HeartPulse,
  History, Layers3, LayoutDashboard, LockKeyhole, LogOut, MapPinned, Menu, PackageSearch, RefreshCcw,
  Search, Settings2, ShieldAlert, ShieldCheck, Sparkles, Table2, Tags, TrendingDown, TrendingUp,
  UserRoundCog, UsersRound, Warehouse, X, XCircle
} from "lucide-react";
import "./BartAdminPortal.css";

const GROUPS=[
 {id:"command",label:"COMMAND",tabs:[["command-center","Command Center",LayoutDashboard],["live-operations","Live Operations",Activity],["branch-network","Branch Network",Building2],["attention-center","Attention Center",ShieldAlert]]},
 {id:"inventory",label:"INVENTORY",tabs:[["inventory-matrix","Inventory Matrix",Table2],["daily-inventory","Daily Inventory",ClipboardCheck],["weekly-inventory","Weekly Inventory",CalendarDays],["global-search","Global Item Search",Search],["sku-explorer","SKU Explorer",PackageSearch],["category-explorer","Category Explorer",Tags]]},
 {id:"intelligence",label:"INTELLIGENCE",tabs:[["stock-movement","Stock Movement",ChartNoAxesCombined],["item-history","Item History",History],["branch-trends","Branch Trends",TrendingUp],["fast-movers","Fast Movers",Gauge],["slow-movers","Slow Movers",TrendingDown],["stock-distribution","Stock Distribution",Warehouse]]},
 {id:"analysis",label:"ANALYSIS",tabs:[["branch-comparison","Branch Comparison",GitCompareArrows],["item-comparison","Item Comparison",Layers3],["date-comparison","Date Comparison",CalendarDays],["category-comparison","Category Comparison",BarChart3],["variance-analyzer","Variance Analyzer",CircleGauge]]},
 {id:"exceptions",label:"EXCEPTIONS",tabs:[["exception-center","Exception Center",AlertTriangle],["zero-stock","Zero Stock",XCircle],["missing-submissions","Missing Data",ShieldAlert],["uncategorized","Uncategorized",Tags],["data-anomalies","Data Anomalies",HeartPulse]]},
 {id:"management",label:"MANAGEMENT",tabs:[["area-managers","Area Managers",UserRoundCog],["manager-branches","Manager Branch View",UsersRound],["area-comparison","Area Comparison",MapPinned]]},
 {id:"reports",label:"REPORTS",tabs:[["report-studio","Report Studio",FileSpreadsheet],["date-range-reports","Date Range Reports",FileChartColumn],["executive-report","Executive Report",Download],["custom-export","Custom Export",Filter],["report-history","Report History",History]]},
 {id:"system",label:"SYSTEM",tabs:[["data-health","Data Health",Database],["system-settings","System Settings",Settings2]]}
];
const ALL=GROUPS.flatMap(g=>g.tabs.map(([id,label,Icon])=>({id,label,Icon,group:g.id})));
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const fmt=v=>new Intl.NumberFormat("en-US",{maximumFractionDigits:2}).format(num(v));
const yesterday=()=>{const d=new Date();d.setDate(d.getDate()-1);return d.toISOString().slice(0,10)};

async function api(path,options={}){const r=await fetch(path,{...options,credentials:"same-origin",headers:{"Content-Type":"application/json",...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.message||`Request failed (${r.status})`);e.status=r.status;throw e}return d}

function Login({onDone,onBack}){const[p,setP]=useState("");const[show,setShow]=useState(false);const[busy,setBusy]=useState(false);const[err,setErr]=useState("");async function submit(e){e.preventDefault();if(!p)return;setBusy(true);setErr("");try{await api("/api/admin/bart/login",{method:"POST",body:JSON.stringify({password:p})});onDone()}catch(x){setErr(x.message)}finally{setBusy(false)}}return <div className="ba-login"><div className="ba-cosmos"><i/><i/><i/><i/></div><motion.form onSubmit={submit} className="ba-login-card" initial={{opacity:0,scale:.9,y:30}} animate={{opacity:1,scale:1,y:0}} transition={{type:"spring",stiffness:120}}><button type="button" className="ba-login-back" onClick={onBack}><ArrowLeft/> BRAND GATEWAY</button><div className="ba-lock-orbit"><span><LockKeyhole/></span><i/><i/></div><small>DAM / BART / RESTRICTED ACCESS</small><h1>Enter the <em>command layer.</em></h1><p>Your password is verified by the Worker. It is never stored in the browser bundle.</p><label>ADMIN PASSWORD</label><div className="ba-password"><LockKeyhole/><input autoFocus value={p} onChange={e=>setP(e.target.value)} type={show?"text":"password"} placeholder="Enter Admin password"/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div>{err&&<div className="ba-login-error"><AlertTriangle/>{err}</div>}<button className="ba-login-submit" disabled={busy}>{busy?<><span className="ba-mini-spin"/> VERIFYING SECURE SESSION</>:<>AUTHENTICATE & ENTER <ArrowRight/></>}</button><div className="ba-login-meta"><span><i/> ENCRYPTED SESSION</span><span>8 HOUR ACCESS WINDOW</span></div></motion.form></div>}

function Loader({label="Synchronizing operations"}){return <div className="ba-load"><div className="ba-load-universe"><i className="l1"/><i className="l2"/><i className="l3"/><span><Command/></span><b/></div><h3>{label}</h3><p>Connecting branch intelligence · Google Sheets · secure Admin channel</p><div className="ba-load-line"><i/></div></div>}
function Metric({label,value,detail,Icon=Activity,tone="cyan"}){return <motion.div className={`ba-metric ${tone}`} whileHover={{y:-7,rotateX:2}}><div className="ba-metric-shine"/><div className="ba-metric-icon"><Icon/></div><span>{label}</span><strong>{value}</strong><small>{detail}</small></motion.div>}
function Head({eyebrow,title,text,children}){return <div className="ba-page-head"><div><span>{eyebrow}</span><h2>{title}</h2><p>{text}</p></div>{children}</div>}
function Empty({text}){return <div className="ba-empty"><PackageSearch/><b>{text}</b></div>}
function Table({rows,branches}){return <div className="ba-table-wrap"><table><thead><tr><th>SKU</th><th>ITEM NAME</th><th>UOM</th>{branches.map(b=><th key={b}>{b}</th>)}<th>TOTAL</th></tr></thead><tbody>{rows.map((r,i)=><tr key={`${r.SKU}-${r["Item Name"]}-${i}`}><td><b>{r.SKU||"—"}</b></td><td>{r["Item Name"]}</td><td>{r.UOM}</td>{branches.map(b=><td key={b} className={num(r[b])===0?"zero":""}>{fmt(r[b])}</td>)}<td className="total">{fmt(r.total??r.Total)}</td></tr>)}</tbody></table></div>}

function CommandCenter({data,date,setTab}){const all=[...(data.daily||[]),...(data.weekly||[])];const unc=all.filter(x=>x.category==="UNCATEGORIZED DETECTED").length;const pct=data.branchCount?Math.round((data.loadedBranchCount||0)/data.branchCount*100):0;return <div className="ba-stack"><motion.section className="ba-command-hero" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}><div className="ba-hero-copy"><span><Sparkles/> LIVE EXECUTIVE COMMAND</span><h1>Operations, <em>in motion.</em></h1><p>BART network intelligence for <b>{date}</b>. Built to surface what matters without mixing brand environments.</p><div className="ba-hero-actions"><button onClick={()=>setTab("inventory-matrix")}><Table2/> OPEN INVENTORY</button><button onClick={()=>setTab("attention-center")}><ShieldAlert/> ATTENTION CENTER</button></div></div><div className="ba-reactor"><i className="rr1"/><i className="rr2"/><i className="rr3"/><div><strong>{pct}%</strong><span>NETWORK LIVE</span></div><b/><b/><b/></div></motion.section><div className="ba-metrics"><Metric label="NETWORK" value={`${data.loadedBranchCount||0}/${data.branchCount||0}`} detail="branches responding" Icon={Building2}/><Metric label="DAILY ITEMS" value={(data.daily||[]).length} detail="inventory records" Icon={ClipboardCheck} tone="violet"/><Metric label="WEEKLY ITEMS" value={(data.weekly||[]).length} detail="inventory records" Icon={CalendarDays} tone="pink"/><Metric label="ATTENTION" value={(data.failedBranches||[]).length+unc} detail="verified data signals" Icon={AlertTriangle} tone="amber"/></div><div className="ba-duo"><section className="ba-panel spectrum"><header><div><span>NETWORK PULSE</span><h3>Branch connectivity</h3></div><button onClick={()=>setTab("data-health")}>DETAILS <ChevronRight/></button></header><div className="ba-pulse-track"><i style={{width:`${pct}%`}}/></div><div className="ba-pulse-values"><b>{data.loadedBranchCount||0} ONLINE</b><span>{(data.failedBranches||[]).length} UNAVAILABLE</span></div></section><section className="ba-panel"><header><div><span>COMMAND SHORTCUTS</span><h3>Move faster</h3></div></header><div className="ba-quick">{[["global-search","Find SKU",Search],["branch-network","Branches",Building2],["exception-center","Exceptions",ShieldAlert],["report-studio","Reports",FileSpreadsheet]].map(([id,l,I])=><button key={id} onClick={()=>setTab(id)}><I/><b>{l}</b><ChevronRight/></button>)}</div></section></div></div>}
function Inventory({data,mode="all"}){const[q,setQ]=useState("");const[cat,setCat]=useState("ALL");const branches=(data.branches||[]).map(b=>b.name);let rows=mode==="daily"?(data.daily||[]):mode==="weekly"?(data.weekly||[]):[...(data.daily||[]),...(data.weekly||[])];rows=rows.filter(r=>(cat==="ALL"||r.category===cat)&&(!q||`${r.SKU} ${r["Item Name"]} ${r.UOM}`.toLowerCase().includes(q.toLowerCase())));return <div className="ba-stack"><Head eyebrow="INVENTORY INTELLIGENCE" title={mode==="all"?"Network Inventory Matrix":`${mode[0].toUpperCase()+mode.slice(1)} Inventory`} text={`${rows.length} visible records across ${branches.length} BART branches.`}/><div className="ba-toolbar"><div><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search SKU, item or UOM..."/></div><select value={cat} onChange={e=>setCat(e.target.value)}><option>ALL</option><option>FOOD ITEMS</option><option>DRY ITEMS</option><option>MISC ITEMS</option><option>UNCATEGORIZED DETECTED</option></select></div><Table rows={rows} branches={branches}/></div>}
function SearchView({data}){const[q,setQ]=useState("");const branches=(data.branches||[]).map(b=>b.name);const all=[...(data.daily||[]),...(data.weekly||[])];const rows=q?all.filter(r=>`${r.SKU} ${r["Item Name"]}`.toLowerCase().includes(q.toLowerCase())):[];return <div className="ba-stack"><Head eyebrow="GLOBAL SEARCH" title="Find anything. Anywhere." text="Search the loaded BART network by SKU or item name."/><div className="ba-mega-search"><Search/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="K242, cups, milk..."/><span>LIVE SNAPSHOT</span></div>{rows.length?<Table rows={rows} branches={branches}/>:<Empty text={q?"No matching item found.":"Start typing to search the network."}/>}</div>}
function Branches({data,onBranch}){return <div className="ba-stack"><Head eyebrow="BRANCH CONSTELLATION" title={`${data.branchCount||0} BART locations`} text="Every branch stays separate. Enter one location for a focused operational view."/><div className="ba-branches">{(data.branches||[]).map((b,i)=><motion.button key={b.code} onClick={()=>onBranch(b)} initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{delay:i*.015}} whileHover={{y:-8}}><div className="ba-branch-glow"/><span>{String(i+1).padStart(2,"0")}</span><i/><div><b>{b.name}</b><small>{b.code} · DATA LINK</small></div><ChevronRight/></motion.button>)}</div></div>}
function Exceptions({data,type="all"}){const all=[...(data.daily||[]),...(data.weekly||[])],branches=(data.branches||[]).map(b=>b.name);let rows=all;if(type==="unc")rows=all.filter(r=>r.category==="UNCATEGORIZED DETECTED");if(type==="zero")rows=all.filter(r=>branches.some(b=>num(r[b])===0));return <div className="ba-stack"><Head eyebrow="FACT-BASED EXCEPTIONS" title={type==="unc"?"Uncategorized Items":type==="zero"?"Zero Stock Signals":"Attention Center"} text="Only signals present in the loaded data are shown here."/><div className="ba-metrics"><Metric label="FAILED BRANCHES" value={(data.failedBranches||[]).length} detail="fetch failures" Icon={Database} tone="amber"/><Metric label="UNCATEGORIZED" value={all.filter(r=>r.category==="UNCATEGORIZED DETECTED").length} detail="classification needed" Icon={Tags} tone="pink"/><Metric label="ZERO-SIGNAL ITEMS" value={all.filter(r=>branches.some(b=>num(r[b])===0)).length} detail="≥1 branch at zero" Icon={XCircle} tone="violet"/></div><Table rows={rows.slice(0,250)} branches={branches}/></div>}
function Health({data}){return <div className="ba-stack"><Head eyebrow="SYSTEM TELEMETRY" title="Admin Data Health" text="Live visibility into the dedicated Admin Google pipeline."/><div className="ba-metrics"><Metric label="LOADED" value={data.loadedBranchCount||0} detail="branch sheets responding" Icon={Database}/><Metric label="EXPECTED" value={data.branchCount||0} detail="master branches" Icon={Building2} tone="violet"/><Metric label="SOURCE" value={(data.source||"GOOGLE").toUpperCase()} detail="aggregation source" Icon={Activity} tone="pink"/></div><section className="ba-panel"><header><div><span>CONNECTION EXCEPTIONS</span><h3>Failed branches</h3></div></header>{(data.failedBranches||[]).length?(data.failedBranches||[]).map((x,i)=><div className="ba-failure" key={i}><XCircle/><b>{typeof x==="string"?x:(x.name||x.branch||"Unknown")}</b><span>{x.error||"Could not read branch sheet"}</span></div>):<div className="ba-success"><ShieldCheck/><div><b>All loaded branches are responding.</b><span>No branch fetch failures in this snapshot.</span></div></div>}</section></div>}
function Generic({tab,data}){const meta=ALL.find(x=>x.id===tab),all=[...(data.daily||[]),...(data.weekly||[])];const top=[...all].sort((a,b)=>num(b.total)-num(a.total)).slice(0,12);return <div className="ba-stack"><Head eyebrow={(meta?.group||"ADMIN").toUpperCase()} title={meta?.label||"Admin Intelligence"} text="This workspace uses the current real inventory snapshot; historical calculations are not fabricated."/><div className="ba-metrics"><Metric label="BRANCHES" value={(data.branches||[]).length} detail="available now" Icon={Building2}/><Metric label="ITEM RECORDS" value={all.length} detail="daily + weekly" Icon={Boxes} tone="violet"/><Metric label="NETWORK QTY" value={fmt(all.reduce((a,r)=>a+num(r.total),0))} detail="snapshot aggregate" Icon={Activity} tone="pink"/></div><section className="ba-panel"><header><div><span>LIVE SNAPSHOT RANKING</span><h3>Largest network quantities</h3></div></header><div className="ba-rank">{top.map((r,i)=><div key={i}><span>{String(i+1).padStart(2,"0")}</span><div><b>{r["Item Name"]}</b><small>{r.SKU||"—"} · {r.UOM}</small></div><strong>{fmt(r.total)}</strong><i style={{width:`${top[0]?.total?Math.max(4,num(r.total)/num(top[0].total)*100):4}%`}}/></div>)}</div></section><div className="ba-notice"><Sparkles/><div><b>{meta?.label} command surface is ready.</b><span>Dedicated historical endpoint can be connected later; the numbers above remain real.</span></div></div></div>}
function BranchWorkspace({branch,data,onBack}){const d=(data.daily||[]).filter(r=>num(r[branch.name])!==0),w=(data.weekly||[]).filter(r=>num(r[branch.name])!==0);return <div className="ba-stack"><button className="ba-backline" onClick={onBack}><ArrowLeft/> ALL BART BRANCHES</button><section className="ba-branch-hero"><div><span>BRANCH COMMAND / {branch.code}</span><h1>{branch.name}</h1><p>Focused operational snapshot without mixing other branches.</p></div><div><i/> DATA CONNECTED</div></section><div className="ba-metrics"><Metric label="DAILY ACTIVE" value={d.length} detail="non-zero items" Icon={ClipboardCheck}/><Metric label="WEEKLY ACTIVE" value={w.length} detail="non-zero items" Icon={CalendarDays} tone="violet"/><Metric label="DAILY QTY" value={fmt(d.reduce((a,r)=>a+num(r[branch.name]),0))} detail="branch quantity" Icon={Boxes} tone="pink"/></div><section className="ba-panel"><header><div><span>BRANCH INVENTORY</span><h3>Current non-zero items</h3></div></header><div className="ba-branch-items">{[...d,...w].map((r,i)=><div key={i}><div><b>{r["Item Name"]}</b><small>{r.SKU||"—"} · {r.UOM}</small></div><strong>{fmt(r[branch.name])}</strong></div>)}</div></section></div>}

export default function BartAdminPortal({onBack}){
 const[auth,setAuth]=useState(null),[data,setData]=useState(null),[error,setError]=useState(""),[loading,setLoading]=useState(false),[tab,setTab]=useState("command-center"),[open,setOpen]=useState("command"),[date,setDate]=useState(yesterday()),[branch,setBranch]=useState(null),[mobile,setMobile]=useState(false);
 useEffect(()=>{api("/api/admin/bart/session").then(x=>setAuth(!!x.authenticated)).catch(()=>setAuth(false))},[]);
 async function load(force=false){setLoading(true);setError("");try{const d=await api(`/api/admin/bart/inventory?date=${encodeURIComponent(date)}${force?"&force=1":""}`);setData(d);setAuth(true)}catch(e){if(e.status===401){setAuth(false);setData(null)}else setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{if(auth===true)load(false)},[auth,date]);
 async function logout(){await api("/api/admin/bart/logout",{method:"POST"}).catch(()=>{});setAuth(false);setData(null)}
 const meta=ALL.find(x=>x.id===tab)||ALL[0];
 function choose(id,g){setTab(id);setOpen(g);setBranch(null);setMobile(false)}
 const content=useMemo(()=>{if(!data)return null;if(branch)return <BranchWorkspace branch={branch} data={data} onBack={()=>setBranch(null)}/>;if(tab==="command-center"||tab==="live-operations")return <CommandCenter data={data} date={date} setTab={setTab}/>;if(tab==="branch-network")return <Branches data={data} onBranch={setBranch}/>;if(tab==="inventory-matrix")return <Inventory data={data}/>;if(tab==="daily-inventory")return <Inventory data={data} mode="daily"/>;if(tab==="weekly-inventory")return <Inventory data={data} mode="weekly"/>;if(tab==="global-search"||tab==="sku-explorer")return <SearchView data={data}/>;if(tab==="attention-center"||tab==="exception-center")return <Exceptions data={data}/>;if(tab==="zero-stock")return <Exceptions data={data} type="zero"/>;if(tab==="uncategorized")return <Exceptions data={data} type="unc"/>;if(tab==="data-health")return <Health data={data}/>;return <Generic tab={tab} data={data}/>},[data,branch,tab,date]);
 if(auth===null)return <div className="ba-root"><Loader label="Verifying Admin session"/></div>;
 if(auth===false)return <Login onDone={()=>setAuth(true)} onBack={onBack}/>;
 return <div className="ba-root"><div className="ba-bg"><i/><i/><i/><i/></div><div className="ba-grid-bg"/>
   <aside className={mobile?"open":""}><div className="ba-side-brand"><div>B</div><section><b>BART</b><span>ADMIN COMMAND</span></section><button onClick={()=>setMobile(false)}><X/></button></div><div className="ba-side-live"><i/> NETWORK SESSION ACTIVE</div><nav>{GROUPS.map(g=><div className="ba-nav-group" key={g.id}><button className="ba-nav-head" onClick={()=>setOpen(open===g.id?"":g.id)}><span>{g.label}</span><ChevronDown className={open===g.id?"rot":""}/></button><AnimatePresence initial={false}>{open===g.id&&<motion.div initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}}>{g.tabs.map(([id,label,Icon])=><button key={id} className={tab===id&&!branch?"active":""} onClick={()=>choose(id,g.id)}><Icon/><span>{label}</span>{tab===id&&!branch&&<motion.i layoutId="nav-active"/>}</button>)}</motion.div>}</AnimatePresence></div>)}</nav><div className="ba-side-bottom"><button onClick={logout}><LogOut/> LOG OUT</button><button onClick={onBack}><ArrowLeft/> BRAND GATEWAY</button></div></aside>
   <div className="ba-shell"><header className="ba-top"><button className="ba-menu" onClick={()=>setMobile(true)}><Menu/></button><div className="ba-breadcrumb"><span>DAM / BART</span><ChevronRight/><b>{branch?branch.name:meta.label}</b></div><div className="ba-top-actions"><label><CalendarDays/><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button onClick={()=>load(true)} disabled={loading}><RefreshCcw className={loading?"spin":""}/> <span>REFRESH</span></button><div className="ba-status"><i/> LIVE</div></div></header><main className="ba-content"><AnimatePresence mode="wait">{loading?<motion.div key="load" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><Loader label="Rebuilding live Admin intelligence"/></motion.div>:error?<motion.div key="err" className="ba-error" initial={{opacity:0,y:15}} animate={{opacity:1,y:0}}><AlertTriangle/><h2>Admin data unavailable</h2><p>{error}</p><button onClick={()=>load(true)}><RefreshCcw/> TRY AGAIN</button></motion.div>:<motion.div key={`${tab}-${branch?.code||"all"}-${date}`} initial={{opacity:0,y:18,filter:"blur(5px)"}} animate={{opacity:1,y:0,filter:"blur(0px)"}} exit={{opacity:0,y:-10}} transition={{duration:.28}}>{content}</motion.div>}</AnimatePresence></main></div>
 </div>
}
